
# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# MySQL
# ===============================

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/async_event
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Gmail SMTP
# ===============================



spring.mail.host=smtp.gmail.com
spring.mail.port=587

#for generating gmail password just go to your gmail
#->manage your google account->security->2 step verification turn on->App passwords->
#->enter your password->next->select app->other->eneter any sample name->generate->
#->password will be generated-> copy this password and enter here

spring.mail.username=akashdange10051993@gmail.com
spring.mail.password=wnbs qhga sxww ijrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Scheduler
metrics.mail.to=akashdange60@gmail.com

#get mail everyday at 9:00 AM 
#metrics.mail.cron=0 0 9 * * ?

#get mail Within 1 minute:
metrics.mail.cron=0 */1 * * * ?


# ===============================
# Async
# ===============================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

# ===============================
# Batch
# ===============================
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoint.metrics.enabled=true

#Delays scheduler by 30 seconds after startup.
spring.task.scheduling.initial-delay=30000





